### ISSUE TITLE
Goal: Argentina SEPA data sets

### ISSUE THREAD

**Issue by markholdex** [trufnetwork/adapters#10]
# [Specs](https://docs.google.com/document/d/1f3tqzRpaNBf3iKEgsRU7Tf1JUnloYC3jqpNx6jCFp_Q/edit?usp=sharing)

# Problem

- [x] trufnetwork/adapters#13
- [x] trufnetwork/adapters#14
- [x] trufnetwork/adapters#15
- [x] trufnetwork/adapters#21
- [x] trufnetwork/adapters#16
- [x] trufnetwork/adapters#17
- [x] trufnetwork/adapters#40
- [x] trufnetwork/adapters#19
- [x] trufnetwork/adapters#26
- [x] trufnetwork/adapters#27

### Repo: `adapters`
- [x] trufnetwork/adapters#24
- [x] trufnetwork/adapters#37
- [x] trufnetwork/adapters#33
- [x] trufnetwork/adapters#46
- [x] https://github.com/trufnetwork/adapters/issues/48

### Repo: `data-provider`
- [x] trufnetwork/adapters#35
- [x] trufnetwork/truf-data-provider#402
- [x] trufnetwork/truf-data-provider#394
- [x] trufnetwork/truf-data-provider#395
- [x] #51
- [x] trufnetwork/truf-data-provider#409

# ETA

- Jan 16 (Thursday)

**Comment by Mantas-M** [comment]
@markholdex have you been able to check historical data for this link? https://datos.produccion.gob.ar/dataset/sepa-precios
I personally only see the last week and do not see a way to get the data from the start 🤔

**Comment by markholdex** [comment]
@Mantas-M while I can see the history of data on the right side of the page, the links seem to open only the fresh data from the current week. There should be a way for us to gather it but I'm not sure what is it at this moment. I'm confident they are storing it somewhere in an archive.

**Comment by Mantas-M** [comment]
Those are my assumptions as well, I have contacted the email which is provided, perhaps they can clear this up.

**Comment by Mantas-M** [comment]
Ah, they actually responded already, seems like it's only possible to get 7 days historical data from here. 

For archive data we should contact have a request submitted https://www.argentina.gob.ar/justicia/derechofacil/leysimple/acceso-la-informacion-publica

**Comment by markholdex** [comment]
@Mantas-M I saw you previously posted the reply from Argentina Gov side. Do you have any answers form them?

**Comment by Mantas-M** [comment]
> @Mantas-M I saw you previously posted the reply from Argentina Gov side. Do you have any answers form them? 

Yes, I removed it as I thought it may not be relevant here and instead described it in the spec. 

But in general, they said we need to make a public data access request as described here: https://www.argentina.gob.ar/justicia/derechofacil/leysimple/acceso-la-informacion-publica

This would allow to get the historical data

**Comment by markholdex** [comment]
@Mantas-M I will check with our team if we have done that already. Will keep you posted here.

**Comment by markholdex** [comment]
@Mantas-M we have received access. We can now request historical data. The only thing is, that the Argentina Gov will manually provide us with .ZIP files like the example above. 

That shouldn't stop us though. Since we know already the format and the type of data we are going to ingest, we just need to look into an adapter that will be able to push the scrapped data to Truf Network by manually being supplied with .ZIP files. 

Let me know if it's clear or you need additional context/info.

**Comment by Mantas-M** [comment]
That makes sense and it was exactly what I was expecting 👌

**Comment by Ivan-TRUF** [comment]
@markholdex @Mantas-M 
Here is a process of ingestion of data on a DAILY basis (v1.0):
STEP 1 > **create daily ingestor**
a) Download ZIP file that will have probably 25+ folders ('comercio') where each will have 3 files daily
b) We need only 'productos' file frome each of those folders > all of those files should be Appended in one 'MASTER productos' table
c) Calculate Average of 'productos_precio_lista' per 'id_producto' > if only one, use that value

STEP 2 > **Ingest historical data**
a) Ingest all the historical data and repeat the 1.b) & 1.c) from STEP 1 for each day that historical data is available

Please start working on Step 1 first and share the result of 1.b) since 1.c) might change, depending on how the data will look like in 'MASTER productos' table

**Comment by rsoury** [comment]
@outerlook - To hop onto this issue Step 1 now.

In the meantime, @Ivan-TRUF - Please provide calculation details for post STEP 1.

**Comment by Ivan-TRUF** [comment]
> @outerlook - To hop onto this issue Step 1 now.
> 
> In the meantime, @Ivan-TRUF - Please provide calculation details for post STEP 1.

I can give you an idea of calculations, since I don't have exact data points yet to determin categories, etc.
It will basically be the average of prices of X amount of tables that are created as a result of the outlined process.

**Comment by outerlook** [comment]
Self assigning as I was informed this is a priority

**Comment by Ivan-TRUF** [comment]
@outerlook what is ETA on this?

**Comment by outerlook** [comment]
Getting the adapter ready: this friday (Dec 20th)

**Comment by outerlook** [comment]
Hey @Ivan-TRUF, here's [the result](https://docs.google.com/spreadsheets/d/1fvYSw_PMtv-CJXS-3riwEzMKIodtwvlojA8VNeGQQCQ/edit?gid=77269284#gid=77269284) (I'll continue to check the logic and manually too)

The format seems as expected?

also confirming:
- from `ALL_PRODUCTS` table, which contains each individual product per store, we aggregated (simple avg) into `AVG_BY_PRODUCT`
- now we're aggregating (simple avg) from `AVG_BY_PRODUCT` to `AVG_BY_CATEGORY`

**Comment by Ivan-TRUF** [comment]
@outerlook yes, this looks good! Keep checking and I will try to get the full list in next few days

**Comment by outerlook** [comment]
hey, I'll need to extend my ETA on this to Dec 26th. Pipeline logic seems to be almost all good, but need more time to adjust details.

**Comment by markholdex** [comment]
@outerlook can you update us on the ETA and if any blockers?

**Comment by outerlook** [comment]
@markholdex yes, wrapping up a PR with the current iteration that can successfully ingest and push to a TN instance. Will be ready in the next 1 hour.

I'll share concerns about fragility on a new issue. But these can be tackled in the new goal where we tackle pagination/rest of categories

**Comment by outerlook** [comment]
@markholdex 
this phase is done with:
- https://github.com/trufnetwork/adapters/issues/17

Argentina adapter is ready at this point. Reliability is not so good with these issues:
- https://github.com/trufnetwork/adapters/issues/19
- https://github.com/trufnetwork/adapters/issues/24
- https://github.com/trufnetwork/adapters/issues/26
- https://github.com/trufnetwork/adapters/issues/27

full categorization is tracked here
- https://github.com/trufnetwork/adapters/issues/33

**Comment by markholdex** [comment]
@outerlook do we have a problem where we track when the solution is deployed live?

**Comment by outerlook** [comment]
@markholdex
> do we have a problem where we track when the solution is deployed live?

 I've split from the implementation issue now

**Comment by outerlook** [comment]
the streams are deployed, and the current content on S3 bucket is available on trufnetwork.

[streams metadata may be found here
](https://github.com/trufnetwork/truf-data-provider/blob/main/assets/categories/argentina_sepa/metadata.csv)

example with CLI:

```
~$ kwil-cli database call get_record date_from:0000-00-00 -n=st8118015b730f044bc4c3685a4681eb --provider https://staging.tsn.truflation.com -o 4710a8d8f0d845da110086812a32de6d90d7ff5c
| date_value |          value          |
+------------+-------------------------+
| 2025-01-03 | 2653.319814898972300000 |
| 2025-01-04 | 2674.140822885463400000 |
| 2025-01-05 | 2689.409123505206500000 |
| 2025-01-06 | 2654.173215987096200000 |
| 2025-01-11 | 2643.145995162187000000 |

~$ kwil-cli database call get_record date_from:0000-00-00 -n=st747bee4cf3a144146de2fb26248a26 --provider https://staging.tsn.truflation.com -o 4710a8d8f0d845da110086812a32de6d90d7ff5c
| date_value |          value          |
+------------+-------------------------+
| 2025-01-03 | 3242.425162424681000000 |
| 2025-01-04 | 3185.316629071276000000 |
| 2025-01-05 | 3199.740688824705600000 |
| 2025-01-06 | 3183.916307193313000000 |
| 2025-01-11 | 3261.615597486488000000 |

```

When complete past data is updated there, I'll reset our streams to pick up all data from start.

However, I recommend that, when enoughly prioritized, we create a goal to have improved quality control over the data. What we still need to handle more properly:

- better reporting of missing categorization on products
- mention when files are corrupted (some of the CSVs have an Error message on it)
- ...etc

**Comment by markholdex** [comment]
Next goal: 
- #52
